/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c742b41e-92b5-4da5-97ee-e6880ea54599",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_qfMnBYmdK",
    "aws_user_pools_web_client_id": "3r1hcmlbqpb9oi9tejpivp1ive",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dktuwawe5rgibbbcvyoyddhm44.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "api60f15dea",
            "endpoint": "https://1oifsy5t65.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        }
    ]
};


export default awsmobile;
